# Generated by Django 2.2.1 on 2019-06-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_antwoorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vereniging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_reason', models.CharField(max_length=64)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vereniging_invites', to='website.Stad')),
                ('stad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Stad')),
            ],
        ),
        migrations.CreateModel(
            name='Verenigingen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('members', models.ManyToManyField(through='website.Vereniging', to='website.Stad')),
            ],
        ),
        migrations.AddField(
            model_name='vereniging',
            name='verenigingen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Verenigingen'),
        ),
    ]
