# Generated by Django 2.2.1 on 2019-06-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190606_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verenigingen',
            name='members',
        ),
        migrations.AddField(
            model_name='verenigingen',
            name='borrel',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='verenigingen',
            name='contributie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='verenigingen',
            name='jaar',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='verenigingen',
            name='leden',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='verenigingen',
            name='locatie',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='verenigingen',
            name='mail',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='verenigingen',
            name='website',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='verenigingen',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verenigingen',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Vereniging',
        ),
    ]
