# Generated by Django 2.2.1 on 2019-06-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190607_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verenigingen',
            name='stad',
        ),
        migrations.AddField(
            model_name='stad',
            name='vovo',
            field=models.ManyToManyField(to='website.Verenigingen'),
        ),
    ]
