# Generated by Django 2.2.1 on 2019-06-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190612_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stad',
            name='vovo',
        ),
        migrations.AddField(
            model_name='stad',
            name='vovo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Verenigingen', to='website.Verenigingen'),
        ),
    ]
