# Generated by Django 2.2.1 on 2019-06-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20190612_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verenigingen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
