# Generated by Django 2.2.1 on 2019-06-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190612_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='verenigingen',
            name='ontgroening',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
