# Generated by Django 2.2.1 on 2019-06-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_verenigingen_ontgroening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stad',
            name='vovo',
        ),
        migrations.AddField(
            model_name='verenigingen',
            name='stad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Stad'),
        ),
    ]
