# Generated by Django 2.2.1 on 2019-06-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20190614_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stad',
            name='vovo',
            field=models.ManyToManyField(related_name='Verenigingen', to='website.Verenigingen'),
        ),
    ]
