# Generated by Django 2.2.1 on 2019-06-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20190614_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stad',
            name='ver',
        ),
        migrations.AddField(
            model_name='stad',
            name='vivi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Verenigingen', to='website.Verenigingen'),
        ),
    ]
