# Generated by Django 2.2.1 on 2019-06-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20190614_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antwoorden',
            name='antwoorden',
        ),
        migrations.AddField(
            model_name='antwoorden',
            name='eens',
            field=models.CharField(default='Eens', max_length=240),
        ),
        migrations.AddField(
            model_name='antwoorden',
            name='geenvanbeide',
            field=models.CharField(default='Geen van Beide', max_length=240),
        ),
        migrations.AddField(
            model_name='antwoorden',
            name='oneens',
            field=models.CharField(default='Oneens', max_length=240),
        ),
        migrations.AlterField(
            model_name='antwoorden',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Vragen'),
        ),
    ]
