# Generated by Django 2.2.1 on 2019-06-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20190616_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='antwoorden',
            name='vraag',
            field=models.CharField(default=1, max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='antwoorden',
            name='eens',
            field=models.CharField(default='Eens', max_length=4),
        ),
        migrations.AlterField(
            model_name='antwoorden',
            name='geenvanbeide',
            field=models.CharField(default='Geen van Beide', max_length=12),
        ),
        migrations.AlterField(
            model_name='antwoorden',
            name='oneens',
            field=models.CharField(default='Oneens', max_length=6),
        ),
        migrations.AlterField(
            model_name='vragen',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
