# Generated by Django 2.2.1 on 2019-06-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20190616_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antwoorden',
            name='geenvanbeide',
            field=models.CharField(default='Geen van Beide', max_length=14),
        ),
    ]
