# Generated by Django 2.2.1 on 2019-06-17 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20190616_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='verenigingen',
            name='url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='verenigingen',
            name='stad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verenigingen', to='website.Stad'),
        ),
    ]
