# Generated by Django 2.2.1 on 2019-06-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_verant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verant',
            name='id',
        ),
        migrations.AddField(
            model_name='verant',
            name='vraag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verant', to='website.Vragen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verant',
            name='vereniging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verant', serialize=False, to='website.Verenigingen'),
        ),
    ]
