# Generated by Django 2.2.1 on 2019-06-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20190619_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='verant',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verant',
            name='vereniging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verant', to='website.Verenigingen'),
        ),
    ]
