# Generated by Django 2.2.1 on 2019-06-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20190619_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='verenigingen',
            name='lan',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='verenigingen',
            name='let',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
