# Generated by Django 2.2.1 on 2019-06-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20190619_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verenigingen',
            old_name='let',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='verenigingen',
            old_name='lan',
            new_name='lng',
        ),
    ]
