# Generated by Django 2.2.1 on 2019-06-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20190619_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='verant',
            name='stad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verant', to='website.Stad'),
            preserve_default=False,
        ),
    ]
