# Generated by Django 2.2.1 on 2019-06-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_verant_stad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vragen',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
