# Generated by Django 2.2.1 on 2019-07-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20190625_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verenigingen',
            old_name='ontgroening',
            new_name='introductietijd',
        ),
    ]
